// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ExamHeader: typeof import('./src/components/exam-header.vue')['default']
  }
}

export { }
